apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    site: blog

spec:
  containers:
    - name: web
      image: nginx

---
apiVersion: v1
kind: Service

metadata:
  name: nginx

spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
